In [5]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[0:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape) 

[5 6 7 8] (4,)
[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [10]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(np.array([[0, 1, 2], [0, 1, 0]]))
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[[1 2]
 [3 4]
 [5 6]]
[[0 1 2]
 [0 1 0]]
[1 4 5]


In [27]:
print(a[1, 0]) # Prints "[1 4 5]"
print([1,0])
print(np.array([[1],[0]]))

# When using integer array indexing, you can reuse the same
# element from the source array:

print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

3
[1, 0]
[[1]
 [0]]
[2 2]


In [30]:
print(np.arange(4))
print(range(4))

[0 1 2 3]
range(0, 4)


In [40]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])
print(b)
print([np.arange(4), b])
print(a[np.arange(4), b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
[array([0, 1, 2, 3]), array([0, 2, 0, 1])]
[ 1  6  7 11]


In [41]:

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [44]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
print(v)
print(v.shape)
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[ 9 10]
(2,)
219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [46]:
v = np.array([[1,2,3]])
print(v)    # Prints "[1 2 3]"
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]
