In [3]:
import numpy as np
std = 1e-4
a = np.random.randn(4,5)
print(a)

[[ 0.22663312  0.03651432  0.95085683  1.50977647 -0.49653912]
 [ 0.04024495 -0.82152051  0.5435729   0.36090194 -1.62687895]
 [ 0.31033509  2.27680335 -0.823149   -0.51365211 -0.88400644]
 [ 0.47708437 -0.76210141  0.33508577  0.92419636  0.91023292]]


In [33]:
f = lambda x: x * (x > 0)
h = {}
h[0] = [np.array([0,-1,3,-4,1,2,3])]

print(type(h[0]))
print(type(np.array([2,3])))
print(h)
h[1] = [np.array([2,3,4])] 
print(h)
print(h[0][0])
print(h[1][0])
print(h[0])
print(type(h[0]))
print(type(h[0][0]))
print(type(h))

<class 'list'>
<class 'numpy.ndarray'>
{0: [array([ 0, -1,  3, -4,  1,  2,  3])]}
{0: [array([ 0, -1,  3, -4,  1,  2,  3])], 1: [array([2, 3, 4])]}
[ 0 -1  3 -4  1  2  3]
[2 3 4]
[array([ 0, -1,  3, -4,  1,  2,  3])]
<class 'list'>
<class 'numpy.ndarray'>
<class 'dict'>
